var stimuli = [
  {
    "Domain": "Politics",
    "Domain_tr": "Politika",
    "Issue": "Economic situation",
    "Issue_tr": "Ekominin durumu",
    "Item": "The economy is good in the country",
    "Item_tr": "Ülkede ekonomi iyi durumda",
    "Disagreement.Level": "LOW",
    "Agree": 17,
    "Disagree": 83,
    "apa2": "Pew Research Center. Across 34 countries, people mostly rate their economies negatively.",
    "link": "https://www.pewresearch.org/short-reads/2024/06/07/economic-ratings-across-34-countries-are-more-negative-than-positive/"
  },
  {
    "Domain": "Morality",
    "Domain_tr": "Ahlak",
    "Issue": "Economic Abortion",
    "Issue_tr": "Kürtaj fikri",
    "Item": "Abortion is acceptable in case of economic difficulties",
    "Item_tr": "Ekonomik zorluk durumunda kürtaj kabul edilebilir",
    "Disagreement.Level": "LOW",
    "Agree": 14.4,
    "Disagree": 73.8,
    "apa2": "Smyrna Tıp Dergisi - 31 - Opinion of Women about Deliberate Abortion",
    "link": "https://smyrnatipdergisi.com/dosyalar_upload/belgeler/K%C3%BCrtaj1487009967.pdf"
  },
  {
    "Domain": "Religion",
    "Domain_tr": "Din",
    "Issue": "Witchcraft belief",
    "Issue_tr": "Büyü inancı",
    "Item": "I would spend money for witchcraft",
    "Item_tr": "Büyü için para harcarım",
    "Disagreement.Level": "LOW",
    "Agree": 6.65,
    "Disagree": 76.65,
    "apa2": "The Journal of Social and Cultural Studies Volume: 5, Issue: 11, Year: 2019, ss. 293-324",
    "link": "https://dergipark.org.tr/en/download/article-file/909985"
  },
  {
    "Domain": "Science",
    "Domain_tr": "Bilim",
    "Issue": "Vaccination opinion",
    "Issue_tr": "Aşı fikri",
    "Item": "I think vaccines are beneficial",
    "Item_tr": "Aşıların faydalı olduğunu düşünürüm",
    "Disagreement.Level": "LOW",
    "Agree": 89.34,
    "Disagree": 6.57,
    "apa2": "Vaccine rejection and hesitation in Turkey Pages 1034-1039 | Received 07 Oct 2019, Accepted 09 Jan 2020, Published online: 06 Feb 2020",
    "link": "https://doi.org/10.1080/21645515.2020.1717182"
  },
  {
    "Domain": "Politics",
    "Domain_tr": "Politika",
    "Issue": "Fair Judiciary",
    "Issue_tr": "Adil yargı",
    "Item": "Fair judiciary system is very important to have",
    "Item_tr": "Adaletli yargı sistemi çok önemlidir",
    "Disagreement.Level": "MED",
    "Agree": 82,
    "Disagree": 18,
    "apa2": "Support for freedom of speech up in several nations since 2015 _ Pew Research Center.pdf",
    "link": "https://www.pewresearch.org/global/2020/02/27/democratic-rights-popular-globally-but-commitment-to-them-not-always-strong/"
  },
  {
    "Domain": "Morality",
    "Domain_tr": "Ahlak",
    "Issue": "Ethanasia morality",
    "Issue_tr": "Ötenazi fikri",
    "Item": "Euthanasia can be used, if the patient is in pain and has a deadly disease",
    "Item_tr": "Eğer hastanın ölümcül bir hastalığı varsa ötenazi kullanılabilir",
    "Disagreement.Level": "MED",
    "Agree": 30.9,
    "Disagree": 42.9,
    "apa2": "Gümüşhane University Journal of Health Sciences:2016;5(1)",
    "link": "https://dergipark.org.tr/tr/download/article-file/220069"
  },
  {
    "Domain": "Religion",
    "Domain_tr": "Din",
    "Issue": "Fortune telling",
    "Issue_tr": "Falcılık inancı",
    "Item": "I believe in fortune telling",
    "Item_tr": "Falcılığa inanırım",
    "Disagreement.Level": "MED",
    "Agree": 18.2,
    "Disagree": 62.7,
    "apa2": "The Journal of Social and Cultural Studies Volume: 5, Issue: 11, Year: 2019, ss. 293-323",
    "link": "https://dergipark.org.tr/en/download/article-file/909983"
  },
  {
    "Domain": "Science",
    "Domain_tr": "Bilim",
    "Issue": "AI Opinion",
    "Issue_tr": "Yapay zeka fikri",
    "Item": "AI will take our jobs from us in the future",
    "Item_tr": "Gelecekte yapay zeka işlerimizi elimizden alacak",
    "Disagreement.Level": "MED",
    "Agree": 69,
    "Disagree": 31,
    "apa2": "Türkiye’nin İlk Yapay Zeka ve Robotik Anketi _ by Deep Learning Türkiye _ Deep Learning Türkiye _ Medium.pdf",
    "link": "https://medium.com/deep-learning-turkiye/t%C3%BCrkiyenin-i%CC%87lk-yapay-zeka-ve-robotik-anketi-568e4128034#:~:text=%C3%87al%C4%B1%C5%9Fanlar%C4%B1n%20ve%20%C3%BCniversite%20%C3%B6%C4%9Frencilerinin%20kat%C4%B1ld%C4%B1%C4%9F%C4%B1,Yapay%20zeka%20art%C4%B1k%20hayat%C4%B1m%C4%B1z%C4%B1n%20i%C3%A7inde."
  },
  {
    "Domain": "Politics",
    "Domain_tr": "Politika",
    "Issue": "Police influence",
    "Issue_tr": "Polisin etkisi",
    "Item": "The influence of the police force is good on th way things are going",
    "Item_tr": "Ülkenin gidişatında polisin etkisi iyi yönde",
    "Disagreement.Level": "HIGH",
    "Agree": 55,
    "Disagree": 42,
    "apa2": "Pew-Research-Center-Turkey-Report-FINAL-July-30-2014.pdf",
    "link": "https://www.pewresearch.org/wp-content/uploads/sites/2/2014/07/Pew-Research-Center-Turkey-Report-FINAL-July-30-2014.pdf"
  },
  {
    "Domain": "Morality",
    "Domain_tr": "Din",
    "Issue": "Extramarital sex",
    "Issue_tr": "Evlilik-dışı ilişki",
    "Item": "Extramarital relationships harms our moral and cultural values",
    "Item_tr": "Evlilik dışı ilişkiler bizim ahlaki ve kültürel değerlerimizi tahrip ediyor.",
    "Disagreement.Level": "HIGH",
    "Agree": 63.6,
    "Disagree": 17.2,
    "apa2": "Opinions of health college students on premarital sex, induced abortions and contraceptive use of young people",
    "link": "https://dergipark.org.tr/tr/download/article-file/152928"
  },
  {
    "Domain": "Religion",
    "Domain_tr": "Din",
    "Issue": "Dream interpretation",
    "Issue_tr": "Rüya yorumlatmak",
    "Item": "I believe in dream interpretation",
    "Item_tr": "Rüya yorumlanmasına inanırım",
    "Disagreement.Level": "HIGH",
    "Agree": 59,
    "Disagree": 41,
    "apa2": "Turkish Faith and Religiosity in Türkiye",
    "link": "https://iiit.org/wp-content/uploads/Turkish-Faith-and-Religiosity-in-T%C3%BCrkiye.pdf"
  },
  {
    "Domain": "Science",
    "Domain_tr": "Bilim",
    "Issue": "Existense of evolution",
    "Issue_tr": "Evrim düşüncesi",
    "Item": "Ibelieve that evolution is a scientific fact",
    "Item_tr": "Evrimin bilimsel bir gerçeklik olduğuna inanırım",
    "Disagreement.Level": "HIGH",
    "Agree": 48,
    "Disagree": 29,
    "apa2": "Turkish Faith and Religiosity in Türkiye",
    "link": "https://iiit.org/wp-content/uploads/Turkish-Faith-and-Religiosity-in-T%C3%BCrkiye.pdf"
  }
]
