var stimuli = [
  {
    "X": 1,
    "Domain": "Politics",
    "Issue": "Trump Performance",
    "Item": "Donald Trump will go down in history as an outstanding president",
    "Agree": 15,
    "Disagree": 85,
    "Source": "ABC News/Washington Post Poll. Jan. 10-13, 2021. N=1,002 adults nationwide. Margin of error ? 3.5.",
    "APA.Source": "Abt Associates (2021). Jan. 10-13, 2021, Washington Post-ABC news poll [Data Set]. https://www.washingtonpost.com/context/jan-10-13-2021-washington-post-abc-news-poll/ab470cba-8e05-4692-af78-4949613740cc/",
    "Disagreement.Level": "high",
    "link": "https://www.washingtonpost.com/context/jan-10-13-2021-washington-post-abc-news-poll/ab470cba-8e05-4692-af78-4949613740cc/",
    "apa2": "Abt Associates (2021). Washington Post-ABC news poll [Data Set].",
    "apa_study": "Abt Associates (2021). Washington Post-ABC news poll [Data Set].",
    "ts1": -84.3915,
    "ts2": 135.6679,
    "source.date": 2021
  },
  {
    "X": 2,
    "Domain": "Politics",
    "Issue": "Riot Agree",
    "Item": "I support the actions of people who stormed the U.S. Capitol",
    "Agree": 8,
    "Disagree": 89,
    "Source": "ABC News/Washington Post Poll. Jan. 10-13, 2021. N=1,002 adults nationwide. Margin of error � 3.5.",
    "APA.Source": "Abt Associates.  (2021). Jan. 10-13, 2021, Washington Post-ABC news poll [Data Set]. https://www.washingtonpost.com/context/jan-10-13-2021-washington-post-abc-news-poll/ab470cba-8e05-4692-af78-4949613740cc/",
    "Disagreement.Level": "high",
    "link": "https://www.washingtonpost.com/context/jan-10-13-2021-washington-post-abc-news-poll/ab470cba-8e05-4692-af78-4949613740cc/",
    "apa2": "Abt Associates (2021). Washington Post-ABC news poll [Data Set].",
    "apa_study": "Abt Associates (2021). Washington Post-ABC news poll [Data Set].",
    "ts1": -74.6387,
    "ts2": 124.2112,
    "source.date": 2021
  },
  {
    "X": 3,
    "Domain": "Politics",
    "Issue": "Drug Reform",
    "Item": "it is not important to reform the country's drug laws",
    "Agree": 18,
    "Disagree": 82,
    "Source": "Bully Pulpit Interactive (2021). Poll for ACLU, American Attitudes on the War on Drug; https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "APA.Source": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set]. ACLU. https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "Disagreement.Level": "medium",
    "link": "https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "apa2": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set].",
    "apa_study": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set].",
    "ts1": -25.4332,
    "ts2": 75.0295,
    "source.date": 2021
  },
  {
    "X": 4,
    "Domain": "Politics",
    "Issue": "Drug Offence",
    "Item": "sentences of people incarcerated for drugs should not be commuted or reduced",
    "Agree": 39,
    "Disagree": 61,
    "Source": "Bully Pulpit Interactive (2021). Poll for ACLU, American Attitudes on the War on Drug; https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "APA.Source": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set]. ACLU. https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "Disagreement.Level": "low",
    "link": "https://www.aclu.org/other/poll-results-american-attitudes-toward-war-drugs",
    "apa2": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set].",
    "apa_study": "Bully Pulpit Interactive. (2021). Poll results on American attitudes toward war on drugs [Data Set].",
    "ts1": -34.4933,
    "ts2": 69.8553,
    "source.date": 2021
  },
  {
    "X": 5,
    "Domain": "Science",
    "Issue": "Time Travel",
    "Item": "humans will someday be able to travel through time",
    "Agree": 39,
    "Disagree": 56,
    "Source": "CBS News (2021). CBS News Poll, Question 3 [31118366.00002]. SSRS. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "SSRS. (2021). CBS News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118366",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31118366",
    "apa2": "SSRS. (2021). CBS News poll [Data Set].",
    "apa_study": "SSRS. (2021). CBS News poll [Data Set].",
    "ts1": 3.9057,
    "ts2": 146.5171,
    "source.date": 2021
  },
  {
    "X": 6,
    "Domain": "Politics",
    "Issue": "Voting Ease",
    "Item": "the government should make it easier for people to vote",
    "Agree": 40,
    "Disagree": 52,
    "Source": "YouGov. (2022). YouGov survey: Issue Positions and Importance [Data Set]. https://d3nkl3psvxxpe9.cloudfront.net/documents/Issue_Positions_and_Importance_poll_results_20240208.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: Issue Positions and Importance [Data Set]. https://d3nkl3psvxxpe9.cloudfront.net/documents/Issue_Positions_and_Importance_poll_results_20240208.pdf",
    "Disagreement.Level": "low",
    "link": "https://d3nkl3psvxxpe9.cloudfront.net/documents/Issue_Positions_and_Importance_poll_results_20240208.pdf",
    "apa2": "YouGov. (2022). YouGov survey: Issue Positions and Importance [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: Issue Positions and Importance [Data Set].",
    "ts1": -57.0369,
    "ts2": 106.8617,
    "source.date": 2024
  },
  {
    "X": 7,
    "Domain": "Politics",
    "Issue": "National Debt",
    "Item": "the national debt is not a problem at all",
    "Agree": 4,
    "Disagree": 95,
    "Source": "Fox News (2023). Fox News Poll, Question 52 [31120191.00051]. Beacon Research/Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2023). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120191 ",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31120191 ",
    "apa2": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "ts1": -59.5954,
    "ts2": 94.1027,
    "source.date": 2023
  },
  {
    "X": 8,
    "Domain": "Politics",
    "Issue": "SS Funding",
    "Item": "the funding of Social Security is not a problem at all",
    "Agree": 11,
    "Disagree": 87,
    "Source": "Fox News (2023). Fox News Poll, Question 52 [31120191.00051]. Beacon Research/Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2023). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120191 ",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31120191 ",
    "apa2": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "ts1": -51.0384,
    "ts2": 92.7595,
    "source.date": 2023
  },
  {
    "X": 9,
    "Domain": "Politics",
    "Issue": "SS Benefits",
    "Item": "Social Security benefits for some future retirees should be reduced",
    "Agree": 16,
    "Disagree": 82,
    "Source": "Fox News (2023). Fox News Poll, Question 52 [31120191.00051]. Beacon Research/Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2023). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120191 ",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31120191 ",
    "apa2": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "ts1": -48.4728,
    "ts2": 83.3712,
    "source.date": 2023
  },
  {
    "X": 10,
    "Domain": "Politics",
    "Issue": "Income Tax",
    "Item": "income tax rates for all Americans should be increased",
    "Agree": 17,
    "Disagree": 80,
    "Source": "Fox News (2023). Fox News Poll, Question 52 [31120191.00051]. Beacon Research/Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2023). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120191 ",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31120191 ",
    "apa2": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2023). Fox News poll [Data Set].",
    "ts1": -71.236,
    "ts2": 76.4571,
    "source.date": 2023
  },
  {
    "X": 11,
    "Domain": "Politics",
    "Issue": "Justice Tenure",
    "Item": "Supreme Court justices should be limited to 18-year terms",
    "Agree": 30,
    "Disagree": 66,
    "Source": "Fox News. (2022). Fox News Poll (Version 1) [Dataset]. Beacon Research; Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research. ",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2022). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119719",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119719",
    "apa2": "Beacon Research & Shaw & Company Research. (2022). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2022). Fox News poll [Data Set].",
    "ts1": -29.3493,
    "ts2": 93.1142,
    "source.date": 2022
  },
  {
    "X": 12,
    "Domain": "Politics",
    "Issue": "Democrat Strategy",
    "Item": "the Democratic Party has a clear plan for dealing with the problems facing the country",
    "Agree": 35,
    "Disagree": 65,
    "Source": "Fox News. (2022). Fox News Poll (Version 1) [Dataset]. Beacon Research; Shaw & Co. Research. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research. ",
    "APA.Source": "Beacon Research & Shaw & Company Research. (2022). Fox News poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119719",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31119719",
    "apa2": "Beacon Research & Shaw & Company Research. (2022). Fox News poll [Data Set].",
    "apa_study": "Beacon Research & Shaw & Company Research. (2022). Fox News poll [Data Set].",
    "ts1": -52.9044,
    "ts2": 119.6854,
    "source.date": 2022
  },
  {
    "X": 13,
    "Domain": "Moral",
    "Issue": "Alcohol Morality",
    "Item": "in general, drinking alcohol is not morally acceptable",
    "Agree": 12,
    "Disagree": 86,
    "Source": "Gallup Organization (2020). Gallup Poll, Question 20 [31117397.00034]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2020). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31117397",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31117397",
    "apa2": "Gallup Organization. (2020). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2020). The Gallup poll [Data Set].",
    "ts1": 0.0472,
    "ts2": 51.2341,
    "source.date": 2020
  },
  {
    "X": 14,
    "Domain": "Moral",
    "Issue": "Marijuana Morality",
    "Item": "in general, smoking marijuana is not morally acceptable",
    "Agree": 28,
    "Disagree": 70,
    "Source": "Gallup Organization (2020). Gallup Poll, Question 20 [31117397.00034]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2020). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31117397",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31117397",
    "apa2": "Gallup Organization. (2020). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2020). The Gallup poll [Data Set].",
    "ts1": -10.7531,
    "ts2": 52.0869,
    "source.date": 2020
  },
  {
    "X": 15,
    "Domain": "Moral",
    "Issue": "Overall Morality",
    "Item": "the state of moral values in the country as a whole is getting better",
    "Agree": 18,
    "Disagree": 78,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": 35.4544,
    "ts2": 25.8936,
    "source.date": 2022
  },
  {
    "X": 16,
    "Domain": "Moral",
    "Issue": "Suicide Morality",
    "Item": "in general, suicide is morally acceptable",
    "Agree": 22,
    "Disagree": 72,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": 13.2544,
    "ts2": 51.7591,
    "source.date": 2022
  },
  {
    "X": 17,
    "Domain": "Moral",
    "Issue": "Gambling Morality",
    "Item": "in general, gambling is morally wrong",
    "Agree": 25,
    "Disagree": 71,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": -2.4923,
    "ts2": 38.9271,
    "source.date": 2022
  },
  {
    "X": 18,
    "Domain": "Moral",
    "Issue": "Gay Morality",
    "Item": "in general, gay or lesbian relations are morally wrong",
    "Agree": 25,
    "Disagree": 71,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": 5.9897,
    "ts2": 28.7003,
    "source.date": 2022
  },
  {
    "X": 19,
    "Domain": "Moral",
    "Issue": "Fur Clothing",
    "Item": "in general, buying or wearing clothing made of animal fur is morally wrong",
    "Agree": 37,
    "Disagree": 60,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": 7.7927,
    "ts2": 66.4095,
    "source.date": 2022
  },
  {
    "X": 20,
    "Domain": "Moral",
    "Issue": "Death Penalty",
    "Item": "in general, the death penalty is morally wrong",
    "Agree": 38,
    "Disagree": 55,
    "Source": "Gallup Organization (2022). Gallup Poll, Question 23 [31119602.00022]. Gallup Organization. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Gallup Organization. (2022). Gallup poll (Version 1) [Data Set]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119602",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31119602",
    "apa2": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "apa_study": "Gallup Organization. (2022). The Gallup poll [Data Set].",
    "ts1": 9.4059,
    "ts2": 42.8766,
    "source.date": 2022
  },
  {
    "X": 21,
    "Domain": "Religion",
    "Issue": "Dead Harm",
    "Item": "people who have died can harm the living",
    "Agree": 18,
    "Disagree": 82,
    "Source": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "APA.Source": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "apa2": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "apa_study": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "ts1": 52.8489,
    "ts2": 69.9437,
    "source.date": 2023
  },
  {
    "X": 22,
    "Domain": "Religion",
    "Issue": "Tarot Belief",
    "Item": "tarot-card readings divine information about the future",
    "Agree": 15,
    "Disagree": 85,
    "Source": "https://today.yougov.com/health/articles/44581-most-americans-hold-some-new-age-beliefs-poll",
    "APA.Source": "YouGov. (2022). Most Americans Hold Some New Age Beliefs. ",
    "Disagreement.Level": "high",
    "link": "https://today.yougov.com/health/articles/44581-most-americans-hold-some-new-age-beliefs-poll",
    "apa2": "YouGov. (2022). Most Americans Hold Some New Age Beliefs. [Dataset]",
    "apa_study": "YouGov. (2022). Most Americans Hold Some New Age Beliefs. [Dataset]",
    "ts1": 7.4347,
    "ts2": 133.2763,
    "source.date": 2022
  },
  {
    "X": 23,
    "Domain": "Religion",
    "Issue": "Small Sin",
    "Item": "even the smallest sin deserves eternal damnation",
    "Agree": 19,
    "Disagree": 78,
    "Source": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "APA.Source": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set]. http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "Disagreement.Level": "medium",
    "link": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "apa2": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "apa_study": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "ts1": 36.7679,
    "ts2": 86.3415,
    "source.date": 2016
  },
  {
    "X": 24,
    "Domain": "Religion",
    "Issue": "Bible Interpretation",
    "Item": "the Bible was not written for each person to interpret as he or she chooses",
    "Agree": 40,
    "Disagree": 51,
    "Source": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "APA.Source": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set]. http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "Disagreement.Level": "low",
    "link": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "apa2": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "apa_study": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "ts1": 7.2615,
    "ts2": 99.3348,
    "source.date": 2016
  },
  {
    "X": 25,
    "Domain": "Religion",
    "Issue": "Ghost Communication",
    "Item": "people who have died can communicate with the living",
    "Agree": 42,
    "Disagree": 58,
    "Source": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "APA.Source": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "apa2": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "apa_study": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "ts1": 59.0388,
    "ts2": 75.674,
    "source.date": 2023
  },
  {
    "X": 26,
    "Domain": "Religion",
    "Issue": "Nature Spirits",
    "Item": "parts of nature, like mountains, rivers, or trees, have spirits",
    "Agree": 48,
    "Disagree": 52,
    "Source": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "APA.Source": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "apa2": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "apa_study": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "ts1": 73.7747,
    "ts2": 96.7891,
    "source.date": 2023
  },
  {
    "X": 27,
    "Domain": "Religion",
    "Issue": "Sex Sin",
    "Item": "sex outside of traditional marriage is not a sin",
    "Agree": 43,
    "Disagree": 49,
    "Source": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "APA.Source": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set]. http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "Disagreement.Level": "low",
    "link": "http://research.lifeway.com/wp-content/uploads/2016/09/Ligonier-State-of-American-Theology-2016-Final-Report.pdf",
    "apa2": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "apa_study": "LifeWay Research. (2016). The state of American theology study 2016 [Data Set].",
    "ts1": 3.0312,
    "ts2": 4.3405,
    "source.date": 2016
  },
  {
    "X": 28,
    "Domain": "Science",
    "Issue": "Vax Chips",
    "Item": "vaccinations for COVID-19 implant microchips to track people",
    "Agree": 9,
    "Disagree": 91,
    "Source": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "APA.Source": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set]. Carsey School of Public Policy. https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "Disagreement.Level": "high",
    "link": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "apa2": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "apa_study": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "ts1": -64.3983,
    "ts2": 154.4013,
    "source.date": 2022
  },
  {
    "X": 29,
    "Domain": "Science",
    "Issue": "Flat Earth",
    "Item": "the Earth is flat, not round",
    "Agree": 10,
    "Disagree": 90,
    "Source": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "APA.Source": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set]. Carsey School of Public Policy. https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "Disagreement.Level": "high",
    "link": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "apa2": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "apa_study": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "ts1": 37.8595,
    "ts2": 164.7133,
    "source.date": 2022
  },
  {
    "X": 30,
    "Domain": "Science",
    "Issue": "Moon Landing",
    "Item": "NASA astronauts did not really land on the Moon",
    "Agree": 12,
    "Disagree": 88,
    "Source": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "APA.Source": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set]. Carsey School of Public Policy. https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "Disagreement.Level": "high",
    "link": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "apa2": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "apa_study": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "ts1": -14.1896,
    "ts2": 170.5362,
    "source.date": 2022
  },
  {
    "X": 31,
    "Domain": "Science",
    "Issue": "Earth Age",
    "Item": "the Earth is not billions of years old",
    "Agree": 25,
    "Disagree": 75,
    "Source": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "APA.Source": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set]. Carsey School of Public Policy. https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "Disagreement.Level": "medium",
    "link": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "apa2": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "apa_study": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "ts1": 24.3609,
    "ts2": 163.5606,
    "source.date": 2022
  },
  {
    "X": 32,
    "Domain": "Science",
    "Issue": "Vaccine Benefits",
    "Item": "vaccines have not mostly been a benefit to human health",
    "Agree": 31,
    "Disagree": 69,
    "Source": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "APA.Source": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set]. Carsey School of Public Policy. https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "Disagreement.Level": "medium",
    "link": "https://carsey.unh.edu/publication/conspiracy-vs-science-a-survey-of-us-public-beliefs",
    "apa2": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "apa_study": "Hamilton, L. (2022). Polar Environment and Science (POLES 2021) [Data Set].",
    "ts1": -48.9612,
    "ts2": 157.0482,
    "source.date": 2022
  },
  {
    "X": 33,
    "Domain": "Politics",
    "Issue": "Federal Oil",
    "Item": "the U.S should get more oil from its federal lands",
    "Agree": 41,
    "Disagree": 36,
    "Source": "https://docs.cdn.yougov.com/m6hvcx4qgt/The_Willow_Project_poll_results.pdf",
    "APA.Source": "YouGov. (2023). YouGov survey: the Willow project [Data Set]. https://docs.cdn.yougov.com/m6hvcx4qgt/The_Willow_Project_poll_results.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/m6hvcx4qgt/The_Willow_Project_poll_results.pdf",
    "apa2": "YouGov. (2023). YouGov survey: the Willow project [Data Set].",
    "apa_study": "YouGov. (2023). YouGov survey: the Willow project [Data Set].",
    "ts1": -80.7541,
    "ts2": 87.7308,
    "source.date": 2023
  },
  {
    "X": 34,
    "Domain": "Religion",
    "Issue": "Immaterial Spirit",
    "Item": "people only have a physical body, and no soul or spirit",
    "Agree": 17,
    "Disagree": 83,
    "Source": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "APA.Source": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/religion/2023/12/07/spirituality-among-americans/",
    "apa2": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "apa_study": "Pew Research Center (2023). Spritiruality among Americans [Data Set]. ",
    "ts1": 65.4259,
    "ts2": 91.1678,
    "source.date": 2023
  },
  {
    "X": 35,
    "Domain": "Moral",
    "Issue": "Eating Meat",
    "Item": "eating meat is always immoral",
    "Agree": 7,
    "Disagree": 79,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -22.5531,
    "ts2": 25.2042,
    "source.date": 2022
  },
  {
    "X": 36,
    "Domain": "Moral",
    "Issue": "Revenge Morality",
    "Item": "it is always morally acceptable to take revenge from someone who has deliberately wronged you",
    "Agree": 8,
    "Disagree": 79,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 20.1272,
    "ts2": 37.9155,
    "source.date": 2022
  },
  {
    "X": 37,
    "Domain": "Moral",
    "Issue": "Cheating Morality",
    "Item": "cheating in a relationship is never immoral",
    "Agree": 9,
    "Disagree": 82,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -10.2008,
    "ts2": 13.904,
    "source.date": 2022
  },
  {
    "X": 38,
    "Domain": "Moral",
    "Issue": "Hungry Steal",
    "Item": "it is always acceptable for someone to steal food if they cannot afford it",
    "Agree": 10,
    "Disagree": 78,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -33.4761,
    "ts2": 36.9306,
    "source.date": 2022
  },
  {
    "X": 39,
    "Domain": "Moral",
    "Issue": "Moral Taint",
    "Item": "people who have done very bad things in their life (for example, a terrible crime) can never be genuinely good people",
    "Agree": 11,
    "Disagree": 75,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 42.2454,
    "ts2": 51.5644,
    "source.date": 2022
  },
  {
    "X": 40,
    "Domain": "Moral",
    "Issue": "Killing Justification",
    "Item": "killing a person can never be justified",
    "Agree": 14,
    "Disagree": 78,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 26.3035,
    "ts2": 53.206,
    "source.date": 2022
  },
  {
    "X": 41,
    "Domain": "Moral",
    "Issue": "Moral Universalism",
    "Item": "moral values are fundamentally the same everywhere",
    "Agree": 15,
    "Disagree": 75,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 43.8164,
    "ts2": 26.222,
    "source.date": 2022
  },
  {
    "X": 42,
    "Domain": "Moral",
    "Issue": "Animal Testing",
    "Item": "it is never morally acceptable to test products on animals before using them on humans",
    "Agree": 36,
    "Disagree": 49,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 0.7165,
    "ts2": 74.1661,
    "source.date": 2022
  },
  {
    "X": 43,
    "Domain": "Moral",
    "Issue": "Sick Stealing",
    "Item": "it is never morally acceptable for someone to steal medication if they cannot afford it",
    "Agree": 37,
    "Disagree": 59,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -29.0636,
    "ts2": 46.3889,
    "source.date": 2022
  },
  {
    "X": 44,
    "Domain": "Moral",
    "Issue": "Rich Morality",
    "Item": "in general, rich people are less moral than poor people",
    "Agree": 37,
    "Disagree": 48,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": 39.5061,
    "ts2": 37.2288,
    "source.date": 2022
  },
  {
    "X": 45,
    "Domain": "Moral",
    "Issue": "Moral Pirating",
    "Item": "downloading pirated media from the internet is always immoral",
    "Agree": 38,
    "Disagree": 44,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -16.0031,
    "ts2": 35.8202,
    "source.date": 2022
  },
  {
    "X": 46,
    "Domain": "Moral",
    "Issue": "Prostitution Morality",
    "Item": "paying for sex is always immoral",
    "Agree": 43,
    "Disagree": 42,
    "Source": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "APA.Source": "YouGov. (2022). YouGov survey: morality [Data Set]. https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "Disagreement.Level": "low",
    "link": "https://docs.cdn.yougov.com/uta5gqhscr/Morality.pdf",
    "apa2": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "apa_study": "YouGov. (2022). YouGov survey: morality [Data Set].",
    "ts1": -8.9541,
    "ts2": 24.7652,
    "source.date": 2022
  },
  {
    "X": 47,
    "Domain": "Science",
    "Issue": "Body Elements",
    "Item": "the elements in the human body are made of stardust from stars millions of years ago",
    "Agree": 37,
    "Disagree": 58,
    "Source": "https://maristpoll.marist.edu/cleveland-museum-of-natural-history-survey/",
    "APA.Source": "The Marist Poll. (2021). Cleveland Museum of Natural History survey [Data Set]. https://maristpoll.marist.edu/wp-content/uploads/2021/09/CMNH-Marist-Poll-National-Survey-September-2021.pdf",
    "Disagreement.Level": "low",
    "link": "https://maristpoll.marist.edu/wp-content/uploads/2021/09/CMNH-Marist-Poll-National-Survey-September-2021.pdf",
    "apa2": "The Marist Poll. (2021). Cleveland Museum of Natural History survey [Data Set].",
    "apa_study": "The Marist Poll. (2021). Cleveland Museum of Natural History survey [Data Set].",
    "ts1": 10.9108,
    "ts2": 175.8581,
    "source.date": 2021
  },
  {
    "X": 48,
    "Domain": "Moral",
    "Issue": "Unmarried Sex",
    "Item": "sex between an unmarried man and woman is generally immoral",
    "Agree": 23,
    "Disagree": 76,
    "Source": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "APA.Source": "Gallup Organization. (2022). Marriage [Data Set]. https://news.gallup.com/poll/117328/Marriage.aspx",
    "Disagreement.Level": "medium",
    "link": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "apa2": "Gallup Organization. (2022). Marriage [Data Set].",
    "apa_study": "Gallup Organization. (2022). Marriage [Data Set].",
    "ts1": 0.9944,
    "ts2": 16.0892,
    "source.date": 2022
  },
  {
    "X": 49,
    "Domain": "Moral",
    "Issue": "Polygamy Moral",
    "Item": "a married person having more than one spouse at the same time is morally acceptable",
    "Agree": 23,
    "Disagree": 75,
    "Source": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "APA.Source": "Gallup Organization. (2022). Marriage [Data Set]. https://news.gallup.com/poll/117328/Marriage.aspx",
    "Disagreement.Level": "medium",
    "link": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "apa2": "Gallup Organization. (2022). Marriage [Data Set].",
    "apa_study": "Gallup Organization. (2022). Marriage [Data Set].",
    "ts1": 16.0107,
    "ts2": 18.7149,
    "source.date": 2022
  },
  {
    "X": 50,
    "Domain": "Moral",
    "Issue": "Unmarried Baby",
    "Item": "it is not moral to have a baby outside of marriage",
    "Agree": 28,
    "Disagree": 70,
    "Source": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "APA.Source": "Gallup Organization. (2022). Marriage [Data Set]. https://news.gallup.com/poll/117328/Marriage.aspx",
    "Disagreement.Level": "medium",
    "link": "https://news.gallup.com/poll/117328/Marriage.aspx",
    "apa2": "Gallup Organization. (2022). Marriage [Data Set].",
    "apa_study": "Gallup Organization. (2022). Marriage [Data Set].",
    "ts1": 15.0984,
    "ts2": 7.4863,
    "source.date": 2022
  },
  {
    "X": 51,
    "Domain": "Politics",
    "Issue": "Marijuana Legality",
    "Item": "the use of marijuana should be illegal",
    "Agree": 32,
    "Disagree": 68,
    "Source": "https://news.gallup.com/poll/1657/Illegal-Drugs.aspx",
    "APA.Source": "Gallup Organization. (2021). Illegal drugs [Data Set]. https://news.gallup.com/poll/1657/Illegal-Drugs.aspx",
    "Disagreement.Level": "medium",
    "link": "https://news.gallup.com/poll/1657/Illegal-Drugs.aspx",
    "apa2": "Gallup Organization. (2021). Illegal drugs [Data Set].",
    "apa_study": "Gallup Organization. (2021). Illegal drugs [Data Set].",
    "ts1": -20.1877,
    "ts2": 61.9999,
    "source.date": 2021
  },
  {
    "X": 52,
    "Domain": "Politics",
    "Issue": "Military Spending",
    "Item": "the U.S is spending too much on immigration",
    "Agree": 35,
    "Disagree": 65,
    "Source": "https://news.gallup.com/poll/1666/Military-National-Defense.aspx",
    "APA.Source": "Gallup Organization. (2023). Military and national defense [Data Set]. https://news.gallup.com/poll/1666/Military-National-Defense.aspx",
    "Disagreement.Level": "low",
    "link": "https://news.gallup.com/poll/1666/Military-National-Defense.aspx",
    "apa2": "Gallup Organization. (2023). Military and national defense [Data Set].",
    "apa_study": "Gallup Organization. (2023). Military and national defense [Data Set].",
    "ts1": -73.1752,
    "ts2": 100.3093,
    "source.date": 2023
  },
  {
    "X": 53,
    "Domain": "Religion",
    "Issue": "God Belief",
    "Item": "God does not exist",
    "Agree": 19,
    "Disagree": 81,
    "Source": "https://news.gallup.com/poll/393737/belief-god-dips-new-low.aspx",
    "APA.Source": "Gallup Organization. (2022). Belief in God in U.S. dips to 81%, a new low [Data Set]. https://news.gallup.com/poll/393737/belief-god-dips-new-low.aspx",
    "Disagreement.Level": "medium",
    "link": "https://news.gallup.com/poll/393737/belief-god-dips-new-low.aspx",
    "apa2": "Gallup Organization. (2022). Belief in God in U.S. dips to 81%, a new low [Data Set].",
    "apa_study": "Gallup Organization. (2022). Belief in God in U.S. dips to 81%, a new low [Data Set].",
    "ts1": 42.0347,
    "ts2": 111.7976,
    "source.date": 2022
  },
  {
    "X": 54,
    "Domain": "Politics",
    "Issue": "Health Insurance",
    "Item": "health coverage is a responsibility of the government",
    "Agree": 40,
    "Disagree": 57,
    "Source": "https://news.gallup.com/poll/4708/Healthcare-System.aspx",
    "APA.Source": "Gallup Organization. (2022). Healthcare system [Data Set]. https://news.gallup.com/poll/4708/Healthcare-System.aspx",
    "Disagreement.Level": "low",
    "link": "https://news.gallup.com/poll/4708/Healthcare-System.aspx",
    "apa2": "Gallup Organization. (2022). Healthcare system [Data Set].",
    "apa_study": "Gallup Organization. (2022). Healthcare system [Data Set].",
    "ts1": -56.7319,
    "ts2": 133.9839,
    "source.date": 2022
  },
  {
    "X": 55,
    "Domain": "Moral",
    "Issue": "Animal Cloning",
    "Item": "it is morally acceptable to clone animals",
    "Agree": 38,
    "Disagree": 58,
    "Source": "https://news.gallup.com/poll/6028/Cloning.aspx",
    "APA.Source": "Gallup Organization. (2022). Cloning [Data Set]. https://news.gallup.com/poll/6028/Cloning.aspx",
    "Disagreement.Level": "low",
    "link": "https://news.gallup.com/poll/6028/Cloning.aspx",
    "apa2": "Gallup Organization. (2022). Cloning [Data Set].",
    "apa_study": "Gallup Organization. (2022). Cloning [Data Set].",
    "ts1": -4.6306,
    "ts2": 65.4585,
    "source.date": 2022
  },
  {
    "X": 56,
    "Domain": "Politics",
    "Issue": "Minimum Wage",
    "Item": "The federal minimum wage is about right",
    "Agree": 13,
    "Disagree": 81,
    "Source": "https://today.yougov.com/topics/politics/articles-reports/2022/12/01/most-americans-think-minimum-wage-is-too-low",
    "APA.Source": "YouGov. (2022). YouGov Survey: the minimum wage [Data Set]. https://docs.cdn.yougov.com/2a5kiqbp5m/toplines_The%20Minimum%20Wage.pdf",
    "Disagreement.Level": "high",
    "link": "https://docs.cdn.yougov.com/2a5kiqbp5m/toplines_The%20Minimum%20Wage.pdf",
    "apa2": "YouGov. (2022). YouGov Survey: the minimum wage [Data Set].",
    "apa_study": "YouGov. (2022). YouGov Survey: the minimum wage [Data Set].",
    "ts1": -84.2532,
    "ts2": 72.0814,
    "source.date": 2022
  },
  {
    "X": 57,
    "Domain": "Religion",
    "Issue": "Devil Belief",
    "Item": "the devil does not exist",
    "Agree": 46,
    "Disagree": 54,
    "Source": "https://www.ipsos.com/sites/default/files/ct/news/documents/2023-05/Ipsos%20Global%20Advisor%20-%20Religion%202023%20Report%20-%2026%20countries.pdf",
    "APA.Source": "IPSOS. (2023). Global religion 2023: Religious beliefs across the world: A 26-country advisor survey [Data Set]. https://www.ipsos.com/sites/default/files/ct/news/documents/2023-05/Ipsos%20Global%20Advisor%20-%20Religion%202023%20Report%20-%2026%20countries.pdf",
    "Disagreement.Level": "low",
    "link": "https://www.ipsos.com/sites/default/files/ct/news/documents/2023-05/Ipsos%20Global%20Advisor%20-%20Religion%202023%20Report%20-%2026%20countries.pdf",
    "apa2": "IPSOS. (2023). Global religion 2023: Religious beliefs across the world: A 26-country advisor survey [Data Set].",
    "apa_study": "IPSOS. (2023). Global religion 2023: Religious beliefs across the world: A 26-country advisor survey [Data Set].",
    "ts1": 48.3078,
    "ts2": 101.83,
    "source.date": 2023
  },
  {
    "X": 58,
    "Domain": "Science",
    "Issue": "COVID Infertility",
    "Item": "COVID-19 vaccines have been shown to cause infertility",
    "Agree": 8,
    "Disagree": 92,
    "Source": "https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "APA.Source": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set]. https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "Disagreement.Level": "high",
    "link": "https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "apa2": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set].",
    "apa_study": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set].",
    "ts1": -57.846,
    "ts2": 162.7746,
    "source.date": 2023
  },
  {
    "X": 59,
    "Domain": "Science",
    "Issue": "Ivermectin Efficacy",
    "Item": "Ivermectin is a safe and effective treatment for COVID-19",
    "Agree": 14,
    "Disagree": 86,
    "Source": "https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "APA.Source": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set]. https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "Disagreement.Level": "high",
    "link": "https://www.kff.org/coronavirus-covid-19/poll-finding/the-covid-19-pandemic-insights-from-three-years-of-kff-polling/",
    "apa2": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set].",
    "apa_study": "Kaiser Family Fondation. (2023). The COVID-19 pandemic: insights from three years of KFF polling [Data Set].",
    "ts1": -63.7634,
    "ts2": 171.5853,
    "source.date": 2023
  },
  {
    "X": 60,
    "Domain": "Science",
    "Issue": "Earth Center",
    "Item": "the center of the Earth is not very hot",
    "Agree": 15,
    "Disagree": 85,
    "Source": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "APA.Source": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set]. https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "Disagreement.Level": "high",
    "link": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "apa2": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "apa_study": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "ts1": 45.8307,
    "ts2": 172.6491,
    "source.date": 2018
  },
  {
    "X": 61,
    "Domain": "Science",
    "Issue": "Radiactivity Source",
    "Item": "not all radioactivity is man-made",
    "Agree": 30,
    "Disagree": 70,
    "Source": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "APA.Source": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set]. https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "Disagreement.Level": "medium",
    "link": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "apa2": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "apa_study": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "ts1": 3.4699,
    "ts2": 181.4842,
    "source.date": 2018
  },
  {
    "X": 62,
    "Domain": "Science",
    "Issue": "Big Bang",
    "Item": "the universe began with a huge explosion",
    "Agree": 39,
    "Disagree": 61,
    "Source": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "APA.Source": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set]. https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "Disagreement.Level": "low",
    "link": "https://www.nsf.gov/statistics/2018/nsb20181/assets/404/science-and-technology-public-attitudes-and-understanding.pdf#%5B%7B%22num%22%3A71%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C40%2C679.5%2C0%5D",
    "apa2": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "apa_study": "National Science Board. (2018). Science and engineering indicators 2018 [Data Set].",
    "ts1": 29.0199,
    "ts2": 148.6232,
    "source.date": 2018
  },
  {
    "X": 63,
    "Domain": "Religion",
    "Issue": "Contraceptive Sin",
    "Item": "using contraceptives is sinful",
    "Agree": 10,
    "Disagree": 63,
    "Source": "https://www.pewresearch.org/religion/2015/09/02/chapter-5-beliefs-about-sin/",
    "APA.Source": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set]. https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "apa2": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set].",
    "apa_study": "Pew Research Center. (2015). Beliefs about sin [Data Set].",
    "ts1": -6.1023,
    "ts2": -4.0826,
    "source.date": 2015
  },
  {
    "X": 64,
    "Domain": "Religion",
    "Issue": "Residence Sin",
    "Item": "living in a house larger than needed is sinful",
    "Agree": 11,
    "Disagree": 64,
    "Source": "https://www.pewresearch.org/religion/2015/09/02/chapter-5-beliefs-about-sin/",
    "APA.Source": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set]. https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "apa2": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set].",
    "apa_study": "Pew Research Center. (2015). Beliefs about sin [Data Set].",
    "ts1": 59.7017,
    "ts2": 43.4916,
    "source.date": 2015
  },
  {
    "X": 65,
    "Domain": "Religion",
    "Issue": "Alcohol Sin",
    "Item": "drinking alcohol is sinful",
    "Agree": 15,
    "Disagree": 58,
    "Source": "https://www.pewresearch.org/religion/2015/09/02/chapter-5-beliefs-about-sin/",
    "APA.Source": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set]. https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/religion/2015/09/02/u-s-catholics-open-to-non-traditional-families/",
    "apa2": "Pew Research Center. (2015). U.S. Catholics open to non-traditional families [Data Set].",
    "apa_study": "Pew Research Center. (2015). Beliefs about sin [Data Set].",
    "ts1": 24.988,
    "ts2": 71.5671,
    "source.date": 2015
  },
  {
    "X": 66,
    "Domain": "Religion",
    "Issue": "Existential Reason",
    "Item": "not everything in life necessarily happens for a reason",
    "Agree": 32,
    "Disagree": 68,
    "Source": "https://www.pewresearch.org/religion/2021/11/23/views-on-the-afterlife/",
    "APA.Source": "Pew Research Center. (2021). Few Americans blame God or say faith has been shaken amid pandemic, other tragedies [Data Set]. https://www.pewresearch.org/religion/2021/11/23/few-americans-blame-god-or-say-faith-has-been-shaken-amid-pandemic-other-tragedies/",
    "Disagreement.Level": "medium",
    "link": "https://www.pewresearch.org/religion/2021/11/23/few-americans-blame-god-or-say-faith-has-been-shaken-amid-pandemic-other-tragedies/",
    "apa2": "Pew Research Center. (2021). Few Americans blame God or say faith has been shaken amid pandemic, other tragedies [Data Set].",
    "apa_study": "Pew Research Center. (2021). Few Americans blame God or say faith has been shaken amid pandemic, other tragedies [Data Set].",
    "ts1": 42.8138,
    "ts2": 138.3622,
    "source.date": 2021
  },
  {
    "X": 67,
    "Domain": "Science",
    "Issue": "Pesticide Safety",
    "Item": "it is safe to eat foods grown with pesticides",
    "Agree": 28,
    "Disagree": 72,
    "Source": "https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "APA.Source": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set]. https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "Disagreement.Level": "medium",
    "link": "https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "apa2": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set].",
    "apa_study": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set].",
    "ts1": -55.1387,
    "ts2": 23.2347,
    "source.date": 2015
  },
  {
    "X": 68,
    "Domain": "Science",
    "Issue": "GMO Safety",
    "Item": "it is safe to eat genetically modified foods",
    "Agree": 37,
    "Disagree": 63,
    "Source": "https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "APA.Source": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set]. https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/science/2015/01/29/public-and-scientists-views-on-science-and-society/",
    "apa2": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set].",
    "apa_study": "Pew Research Center. (2015). Public and scientists' views on science and society [Data Set].",
    "ts1": -55.9443,
    "ts2": 31.1687,
    "source.date": 2015
  },
  {
    "X": 69,
    "Domain": "Science",
    "Issue": "Water Boil",
    "Item": "water boils at lower temperatures at higher altitudes",
    "Agree": 34,
    "Disagree": 66,
    "Source": "https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "APA.Source": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set]. https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "apa2": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set].",
    "apa_study": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set].",
    "ts1": 52.4497,
    "ts2": 183.1556,
    "source.date": 2015
  },
  {
    "X": 70,
    "Domain": "Science",
    "Issue": "Amplitude Loudness",
    "Item": "amplitude or height determines loudness in a sound wave",
    "Agree": 35,
    "Disagree": 65,
    "Source": "https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "APA.Source": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set]. https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/science/2015/09/10/what-the-public-knows-and-does-not-know-about-science/",
    "apa2": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set].",
    "apa_study": "Pew Research Center. (2015). A look at what the public knows and does not know about science [Data Set].",
    "ts1": -10.1849,
    "ts2": 111.1122,
    "source.date": 2015
  },
  {
    "X": 71,
    "Domain": "Politics",
    "Issue": "Gun Laws",
    "Item": "gun laws should be less strict than they are today",
    "Agree": 14,
    "Disagree": 85,
    "Source": "https://www.pewresearch.org/short-reads/2021/09/13/key-facts-about-americans-and-guns/",
    "APA.Source": "Pew Research Center. (2021). Key facts about Americans and guns [Data Set]. https://www.pewresearch.org/short-reads/2021/09/13/key-facts-about-americans-and-guns/",
    "Disagreement.Level": "high",
    "link": "https://www.pewresearch.org/short-reads/2021/09/13/key-facts-about-americans-and-guns/",
    "apa2": "Pew Research Center. (2021). Key facts about Americans and guns [Data Set].",
    "apa_study": "Pew Research Center. (2021). Key facts about Americans and guns [Data Set].",
    "ts1": -17.3119,
    "ts2": 85.1625,
    "source.date": 2021
  },
  {
    "X": 72,
    "Domain": "Politics",
    "Issue": "Slavery Reparations",
    "Item": "descendants of people enslaved in the U.S. should be repaid in some way",
    "Agree": 30,
    "Disagree": 68,
    "Source": "https://www.pewresearch.org/short-reads/2022/11/28/black-and-white-americans-are-far-apart-in-their-views-of-reparations-for-slavery/ft_22-11-09_reparations_1/",
    "APA.Source": "Pew Research Center. (2022). 77% of Black Americans 'compared with 18% of White Americans ' support reparations for descendants of enslaved people [Data Set]. https://www.pewresearch.org/short-reads/2022/11/28/black-and-white-americans-are-far-apart-in-their-views-of-reparations-for-slavery/ft_22-11-09_reparations_1/",
    "Disagreement.Level": "medium",
    "link": "https://www.pewresearch.org/short-reads/2022/11/28/black-and-white-americans-are-far-apart-in-their-views-of-reparations-for-slavery/ft_22-11-09_reparations_1/",
    "apa2": "Pew Research Center. (2022). 77% of Black Americans 'compared with 18% of White Americans ' support reparations for descendants of enslaved people [Data Set].",
    "apa_study": "Pew Research Center. (2022). Beliefs about reparations [Data Set].",
    "ts1": -45.8534,
    "ts2": 58.7065,
    "source.date": 2022
  },
  {
    "X": 73,
    "Domain": "Science",
    "Issue": "Climate Change",
    "Item": "the earth is getting warmer mostly due to natural patterns",
    "Agree": 24,
    "Disagree": 76,
    "Source": "https://www.pewresearch.org/short-reads/2023/02/09/the-pope-is-concerned-about-climate-change-how-do-u-s-catholics-feel-about-it/",
    "APA.Source": "Pew Research Center. (2023). The pope is concerned about climate change. how do U.S. Catholics feel about it? [Data Set]. https://www.pewresearch.org/short-reads/2023/02/09/the-pope-is-concerned-about-climate-change-how-do-u-s-catholics-feel-about-it/",
    "Disagreement.Level": "medium",
    "link": "https://www.pewresearch.org/short-reads/2023/02/09/the-pope-is-concerned-about-climate-change-how-do-u-s-catholics-feel-about-it/",
    "apa2": "Pew Research Center. (2023). The pope is concerned about climate change. how do U.S. Catholics feel about it? [Data Set].",
    "apa_study": "Pew Research Center. (2023). Belief tracking poll [Data Set].",
    "ts1": 53.6538,
    "ts2": 167.1866,
    "source.date": 2023
  },
  {
    "X": 74,
    "Domain": "Politics",
    "Issue": "Tax Rates",
    "Item": "tax rates on household incomes over $400,000 should not be raised",
    "Agree": 37,
    "Disagree": 61,
    "Source": "https://www.pewresearch.org/short-reads/2023/04/07/top-tax-frustrations-for-americans-the-feeling-that-some-corporations-wealthy-people-dont-pay-fair-share/",
    "APA.Source": "Pew Research Center. (2023). The pope is concerned about climate change. how do U.S. Catholics feel about it? [Data Set]. https://www.pewresearch.org/short-reads/2023/02/09/the-pope-is-concerned-about-climate-change-how-do-u-s-catholics-feel-about-it/",
    "Disagreement.Level": "low",
    "link": "https://www.pewresearch.org/short-reads/2023/02/09/the-pope-is-concerned-about-climate-change-how-do-u-s-catholics-feel-about-it/",
    "apa2": "Pew Research Center. (2023). The pope is concerned about climate change. how do U.S. Catholics feel about it? [Data Set].",
    "apa_study": "Pew Research Center. (2023). Belief tracking poll [Data Set].",
    "ts1": -68.7223,
    "ts2": 68.8723,
    "source.date": 2023
  },
  {
    "X": 75,
    "Domain": "Science",
    "Issue": "Antibiotic Bacterial",
    "Item": "antibiotics are not effective against bacterial infections",
    "Agree": 10,
    "Disagree": 90,
    "Source": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "APA.Source": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set]. https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "Disagreement.Level": "high",
    "link": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "apa2": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set].",
    "apa_study": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance [Data Set].",
    "ts1": -42.5326,
    "ts2": 185.4253,
    "source.date": 2012
  },
  {
    "X": 76,
    "Domain": "Science",
    "Issue": "Solar Rotation",
    "Item": "it takes one day for the Earth to go around the Sun",
    "Agree": 18,
    "Disagree": 75,
    "Source": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "APA.Source": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set]. https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "Disagreement.Level": "medium",
    "link": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "apa2": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set].",
    "apa_study": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance [Data Set].",
    "ts1": 29.3301,
    "ts2": 173.5389,
    "source.date": 2012
  },
  {
    "X": 77,
    "Domain": "Science",
    "Issue": "Antibiotic Viral",
    "Item": "antibiotics are not at all effective against viral infections",
    "Agree": 42,
    "Disagree": 58,
    "Source": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "APA.Source": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set]. https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "Disagreement.Level": "low",
    "link": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "apa2": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set].",
    "apa_study": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance [Data Set].",
    "ts1": -49.3158,
    "ts2": 181.9489,
    "source.date": 2012
  },
  {
    "X": 78,
    "Domain": "Science",
    "Issue": "Specie Documentation",
    "Item": "scientists have not documented most of the species on Earth",
    "Agree": 46,
    "Disagree": 51,
    "Source": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "APA.Source": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set]. https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "Disagreement.Level": "low",
    "link": "https://www.pewtrusts.org/~/media/assets/2012/11/12/abxpollsummarypdf.pdf",
    "apa2": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance: A report of findings from a national survey and two focus groups [Data Set].",
    "apa_study": "Hart Research Associates And Public Opinion Strategies. (2012). Americans' knowledge of and attitudes toward antibiotic resistance [Data Set].",
    "ts1": -18.6351,
    "ts2": 159.789,
    "source.date": 2012
  },
  {
    "X": 79,
    "Domain": "Religion",
    "Issue": "God Control",
    "Item": "God observes but does not control what happens on Earth",
    "Agree": 37,
    "Disagree": 63,
    "Source": "https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "APA.Source": "Harris Interactive (2013). Americans' belief in God, miracles and heaven declines [Data Set]. Cision PR Newswire. https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "Disagreement.Level": "low",
    "link": "https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "apa2": "Harris Interactive (2013). Americans' belief in God, miracles and heaven declines [Data Set].",
    "apa_study": "Harris Interactive (2013). Religious belief poll [Data Set].",
    "ts1": 40.9849,
    "ts2": 124.1061,
    "source.date": 2013
  },
  {
    "X": 80,
    "Domain": "Religion",
    "Issue": "God Gender",
    "Item": "God is both male and female",
    "Agree": 10,
    "Disagree": 71,
    "Source": "https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "APA.Source": "Harris Interactive (2013). Americans' belief in God, miracles and heaven declines [Data Set]. Cision PR Newswire. https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "Disagreement.Level": "high",
    "link": "https://www.prnewswire.com/news-releases/americans-belief-in-god-miracles-and-heaven-declines-236051651.html",
    "apa2": "Harris Interactive (2013). Religious belief poll [Data Set].",
    "apa_study": "Harris Interactive (2013). Americans' belief in God, miracles and heaven declines [Data Set].",
    "ts1": 29.8418,
    "ts2": 109.8638,
    "source.date": 2013
  },
  {
    "X": 81,
    "Domain": "Religion",
    "Issue": "Witchcraft Belief",
    "Item": "witches or spells exist",
    "Agree": 21,
    "Disagree": 79,
    "Source": "Ipsos (2021). Ipsos Understanding Society: Wave 24 October 2021, Question 6 [31118753.00005]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "IPSOS. (2021). IPSOS understanding society: wave 24 October 2021 (Version 2) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118753",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31118753",
    "apa2": "IPSOS. (2021). IPSOS understanding society: wave 24 [Dataset].",
    "apa_study": "IPSOS. (2021). IPSOS understanding society: wave 24 October 2021 (Version 2) [Dataset].",
    "ts1": 69.7793,
    "ts2": 107.5277,
    "source.date": 2021
  },
  {
    "X": 82,
    "Domain": "Science",
    "Issue": "AI Economy",
    "Item": "having machines with the ability to think for themselves will help the economy",
    "Agree": 19,
    "Disagree": 73,
    "Source": "Monmouth University Polling Institute (2023). Monmouth University Poll, Question 24 [31120110.00024]. Monmouth University Polling Institute. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Monmouth University Polling Institute. (2023). Monmouth University poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120110",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31120110",
    "apa2": "Monmouth University Polling Institute. (2023). Monmouth University poll [Dataset].",
    "apa_study": "Monmouth University Polling Institute. (2023). Monmouth University poll [Dataset].",
    "ts1": -18.9158,
    "ts2": 129.5453,
    "source.date": 2023
  },
  {
    "X": 83,
    "Domain": "Science",
    "Issue": "AI News",
    "Item": "there will never be a time when entire news articles will be written by artificial intelligence",
    "Agree": 24,
    "Disagree": 72,
    "Source": "Monmouth University Polling Institute (2023). Monmouth University Poll, Question 24 [31120110.00024]. Monmouth University Polling Institute. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Monmouth University Polling Institute. (2023). Monmouth University poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120110",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31120110",
    "apa2": "Monmouth University Polling Institute. (2023). Monmouth University poll [Dataset].",
    "apa_study": "Monmouth University Polling Institute. (2023). Monmouth University poll [Dataset].",
    "ts1": -15.4989,
    "ts2": 139.2209,
    "source.date": 2023
  },
  {
    "X": 84,
    "Domain": "Religion",
    "Issue": "God Influence",
    "Item": "God or a higher power directly influences everything that occurs in the world",
    "Agree": 21,
    "Disagree": 78,
    "Source": "Pew Research Center for the People & the Press (2021). Pew Research Center's American Trends Panel Poll, Question 56 [31118724.00056]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2021). Pew Research Center's American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118724",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31118724",
    "apa2": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "ts1": 32.1731,
    "ts2": 129.0185,
    "source.date": 2021
  },
  {
    "X": 85,
    "Domain": "Religion",
    "Issue": "Direct Revelation",
    "Item": "it is impossible to receive a direct revelation from a higher power",
    "Agree": 29,
    "Disagree": 67,
    "Source": "Pew Research Center for the People & the Press (2021). Pew Research Center's American Trends Panel Poll, Question 56 [31118724.00056]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2021). Pew Research Center's American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118724",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31118724",
    "apa2": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "ts1": 22.3852,
    "ts2": 128.243,
    "source.date": 2021
  },
  {
    "X": 86,
    "Domain": "Religion",
    "Issue": "Prayer Answered",
    "Item": "it is impossible to get a definite answer to a specific prayer request",
    "Agree": 31,
    "Disagree": 67,
    "Source": "Pew Research Center for the People & the Press (2021). Pew Research Center's American Trends Panel Poll, Question 56 [31118724.00056]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2021). Pew Research Center's American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118724",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31118724",
    "apa2": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "ts1": 15.7221,
    "ts2": 117.8664,
    "source.date": 2021
  },
  {
    "X": 87,
    "Domain": "Religion",
    "Issue": "Hell Belief",
    "Item": "Hell does not exist",
    "Agree": 36,
    "Disagree": 62,
    "Source": "Pew Research Center for the People & the Press (2021). Pew Research Center's American Trends Panel Poll, Question 56 [31118724.00056]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2021). Pew Research Center's American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31118724",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31118724",
    "apa2": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2021). Pew Research Center's American trends panel poll [Dataset].",
    "ts1": 52.3627,
    "ts2": 109.9207,
    "source.date": 2021
  },
  {
    "X": 88,
    "Domain": "Religion",
    "Issue": "Scripture Literality",
    "Item": "holy scripture is the word of God and should be taken literally, word for word",
    "Agree": 22,
    "Disagree": 76,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll, Question 22 [31120005.00021]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120005",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31120005",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": 16.485,
    "ts2": 98.0415,
    "source.date": 2022
  },
  {
    "X": 89,
    "Domain": "Religion",
    "Issue": "Doomsday Belief",
    "Item": "we are living in the end times",
    "Agree": 39,
    "Disagree": 58,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll, Question 22 [31120005.00021]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31120005",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31120005",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": 11.9965,
    "ts2": 149.2187,
    "source.date": 2022
  },
  {
    "X": 90,
    "Domain": "Politics",
    "Issue": "CDC COVID",
    "Item": "public health officials (e.g., at CDC) have done an excellent job of responding to COVID",
    "Agree": 13,
    "Disagree": 87,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119874",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31119874",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": -57.8642,
    "ts2": 144.643,
    "source.date": 2022
  },
  {
    "X": 91,
    "Domain": "Politics",
    "Issue": "Scientist Influence",
    "Item": "scientists have too much influence in public policy debates",
    "Agree": 19,
    "Disagree": 81,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119874",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119874",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": -33.7819,
    "ts2": 137.4426,
    "source.date": 2022
  },
  {
    "X": 92,
    "Domain": "Politics",
    "Issue": "Ukraine Support",
    "Item": "the US is providing too much support to Ukraine",
    "Agree": 20,
    "Disagree": 80,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119874",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119874",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": -81.7095,
    "ts2": 106.0836,
    "source.date": 2022
  },
  {
    "X": 93,
    "Domain": "Politics",
    "Issue": "Bible Influence",
    "Item": "the Bible should have no influence on laws in the US",
    "Agree": 36,
    "Disagree": 64,
    "Source": "Pew Research Center for the People & the Press (2022). Pew American Trends Panel Poll. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Pew American trends panel poll (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119874",
    "Disagreement.Level": "low",
    "link": "https://doi.org/10.25940/ROPER-31119874",
    "apa2": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "apa_study": "Pew Research Center. (2022). Pew American trends panel poll [Dataset].",
    "ts1": -2.8329,
    "ts2": 93.9096,
    "source.date": 2022
  },
  {
    "X": 94,
    "Domain": "Science",
    "Issue": "Media Mind-change",
    "Item": "social media is very effective at changing people's minds about political issues",
    "Agree": 16,
    "Disagree": 83,
    "Source": "Pew Research Center for the People & the Press (2022). Spring 2022 Global Attitudes Survey, Question 7 [31119465.00086]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "Pew Research Center. (2022). Spring 2022 global attitudes survey (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119465",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31119465",
    "apa2": "Pew Research Center. (2022). Spring 2022 global attitudes survey [Dataset].",
    "apa_study": "Pew Research Center. (2022). Spring 2022 global attitudes survey [Dataset].",
    "ts1": -36.999,
    "ts2": 127.2625,
    "source.date": 2022
  },
  {
    "X": 95,
    "Domain": "Politics",
    "Issue": "Electoral College",
    "Item": "presidential elections should be decided based on the electoral college, not the popular vote",
    "Agree": 30,
    "Disagree": 65,
    "Source": "PRRI (2022). PRRI American Values Survey, Question 100 [31119979.00099]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "PRRI. (2022). PRRI American values survey (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119979",
    "Disagreement.Level": "medium",
    "link": "https://doi.org/10.25940/ROPER-31119979",
    "apa2": "PRRI. (2022). PRRI American values survey [Dataset].",
    "apa_study": "PRRI. (2022). PRRI American values survey [Dataset].",
    "ts1": -24.782,
    "ts2": 110.7042,
    "source.date": 2022
  },
  {
    "X": 96,
    "Domain": "Religion",
    "Issue": "Holy America",
    "Item": "God intended America to be a new promised land for European Christians",
    "Agree": 10,
    "Disagree": 83,
    "Source": "PRRI (2022). PRRI American Values Survey, Question 100 [31119979.00099]. Ipsos. Cornell University, Ithaca, NY: Roper Center for Public Opinion Research.",
    "APA.Source": "PRRI. (2022). PRRI American values survey (Version 1) [Dataset]. Roper Center for Public Opinion Research. https://doi.org/10.25940/ROPER-31119979",
    "Disagreement.Level": "high",
    "link": "https://doi.org/10.25940/ROPER-31119979",
    "apa2": "PRRI. (2022). PRRI American values survey [Dataset].",
    "apa_study": "PRRI. (2022). PRRI American values survey [Dataset].",
    "ts1": 56.4511,
    "ts2": 127.334,
    "source.date": 2022
  }
]
